### ISSUE TITLE
Prune mode does not work on latest release

### ISSUE THREAD

**Issue by pinpins** [bitcoin-sv/bitcoin-sv#214] opened 2021-08-11 18:02 UTC
Prune mode does not work on latest release 1.0.8

**Comment by BobZombiE69** [comment] 2021-08-20 15:38
yes for me prune node is not working in version 1.0.7 and 1.0.8

**Comment by Gamaroff** [comment] 2021-08-23 07:50
I am having the same problem.
Glad its not just me!

**Comment by matra774** [comment] 2021-08-23 08:45
@pinpins @BobZombiE69 @Gamaroff  To get a useful answer, please provide more detailed info about problems you are facing (answer questions that are listed when you create a new github issue). What does "prune node is not working mean". Did the app crash? Does ti just ignore the parameters? How did you observe this? Is any related error logged in bitcoind.log file....

**Comment by BobZombiE69** [comment] 2021-08-23 09:54
I was on version 1.0.4 for months , with no-prune , without any problems.
10 days ago i used prune=5000 , then suddenly docker crashed with nospecial error in logs , 
and when i start the docker again, it says .... 

> use -reindex or -reindex-chainstate 
and as you it will sync the block chain from the begining, and it will take days to sync again.

i restored last backup for about 10 times, try different versions, 1.0.6 to 1.0.8
again and again after few hours , the docker crashes and some error like ....###.blk  file missing/corrupt and "try to -reindex" message again

i updated docker to latest version , it worked for about 1 day then again crashed and some files missing or corrupt and ....

hopefully i have a working backup to restore from about one weeks ago

i am sure that BSV prune mode has some problems
because on this machine i have BCH-N and BTC  nodes in prune mode working perfectly for about a year with no problem, only BSV has this problem.

I will try to send you a complete log next time this happen

**Comment by matra774** [comment] 2021-08-23 11:29
Thanks, @BobZombiE69. We are currently not aware of any problems with prune mode. 

Please make sure that your system  meet recommended requirements listed here: https://bitcoinsv.io/documentation/miners/system-requirements/. 

Docker/OS can terminate the process if there are not enough system resources available - and there were some pretty large blocks on BSV mainnet recently (gigabytes, not megabytes).

You might also want to follow instructions listed here: https://github.com/bitcoin-sv/bitcoin-sv/blob/master/doc/core-dumps.md to collect core dumps if  bitcoind  is crashing. This can be used by developers to extract more info if needed.

**Comment by BobZombiE69** [comment] 2021-08-23 11:37
Thank you very much.
I didn't know about gigabyte size blocks !
So maybe  that could be the reason bchn and btc is working fine on the same machine, because their block size are much smaller.

**Comment by BobZombiE69** [comment] 2021-08-23 16:29
Thank you very much.
**I can confirm that the system went down low on RAM (out of memory) , so OOM KILLER decides to kill the bitcoind process of bitcoin-sv**
my previous settings was:
blockmaxsize=4000000000 
maxmempool=8000 #8G
dbcache=8192 #8G

for now i will try to reduce the ram usage and test if it can help, here are my new settings:

maxmempool=4000 #4G
dbcache=4192 #4G
blockmaxsize=8000000

i'm using this node for mining pool, i hope there won't be any issue for miners with these settings.

**Comment by Gamaroff** [comment] 2021-08-24 07:50
I am also experiencing the same problem on 1.0.8

**Comment by Klar** [comment] 2021-09-15 08:38
same for me, pruning does not work i.e bigger disk size than configured via the bitcoin.conf setting (prune=20000).

Node Version 1.0.8

Worked before but the node crashed (because of the attacking forks) and had to reindex, since then pruning does not work.

**Comment by Polve** [comment] 2021-09-15 10:43
Same problem with me, I had to reindex everything with the node unusable for days

**Comment by Danconnolly** [comment] 2021-09-16 18:06
Thank you for reporting this issue, it is being investigated.

**Comment by Polve** [comment] 2021-09-17 20:53
Even after full reindex the daemon works for a few days and then new problems arise: it seems like it doesn't find the block files anymore after a restart:

> Unable to open file /storage/bsv/chain/blocks/blk05945.dat

**Comment by BobZombiE69** [comment] 2021-09-17 21:33
after using a way bigger disk space than required, and adding more RAM than before , the problem has solved for me (at least  for now)

**Comment by BobZombiE69** [comment] 2021-09-20 15:35
i can confirm that the prune mode size is exceeding the value in bitcoin.conf
so after reboot or node stop/start, most of the time it needs reindex, cause it's looking for at least one .blk file that does not exist on the disk anymore

**Comment by matra774** [comment] 2021-09-20 18:08
>i can confirm that the prune mode size is exceeding the value in bitcoin.conf

What is the target prune size in bitcoind.conf and what is the size of *.blk files.

Please note that the prune configuration value is just a guideline since:
- blocks can be very big (giga byes) and bitcoind can not delete half of block
- blk file can contain multiple blocks
- blocks in blk files are not necessary sorted by height (they are sorted by arrival order, which might not be the same)
- There is minimum number of blocks (measured as distance from current best height) that will always be kept in files. Coupled with the restriction above this can further limit which files can be deleted.

**Comment by lifengmds** [comment] 2021-10-09 04:23
I had the same issue, and also it crashed many times at some points when disks & mem usage were high but less than 90%.

**Comment by Danconnolly** [comment] 2021-11-12 10:44
The issue has been confirmed. The software will require a large amount of disk space duing first initialization (initial block download) but it will steadily reduce disk usage once it has reached the tip.

Our recommendation at the moment is to temporarily assign a large drive which can be replaced with a smaller one after the disk space has dropped.

The issue is being worked on and will be fixed in a future version.

**Closed** 2021-12-02 10:55 UTC
Labels: backlog

**Comment by Klar** [comment] 2021-12-16 07:55
As this is closed, is this fixed in the new release? Haven't seen anything about it in the changelog.

i.e how can we subscribe to get informed when this is fixed

**Comment by CassClark** [comment] 2021-12-16 18:31
@Klar we've provided the workaround.  The fix will be in a future release.

**Comment by afomi** [comment] 2022-03-13 08:07
I lost a few hours maxxing out volumes well-under the prune limit, and found my way here.

Seems like this is still an open issue. 
Is there another issue tracking the `require a large amount of disk space during first initialization` ?

**Comment by Danconnolly** [comment] 2022-03-13 10:10
This is fixed in the next release.
